schema-version: v2
kind: plugin
metadata:
  name: stk-test
  display-name: stk-test
  description: Describe your plugin explaining its purpose
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
  stk-projects-only: false
  inputs:
    - label: nome de pessoa
      name: resource_name
      type: text
      required: true
      
